# Configuration file for runs

CANVAS_SIZE = 100
NUMERIC_SCALE_FACTOR = 8
TEST_FUNCTION = "BEAM_HAUSDORFF"
NUMBER_OF_GENERATIONS = 8
ALPHA = 0.2 # survival rate
PROGRAMS_PER_GENERATION = 80
P_SIGMA_RESET = 0.2
SIGMA_DECAY_FACTOR = 0.85
SIGMA_RESET_VALUE = 40.0 # float
DATA_WRITER = None
SHOW_GRAPHS = True
RUN_ID = "0038"