# Configuration file for runs

CANVAS_SIZE = 80
NUMERIC_SCALE_FACTOR = 1

P_SIGMA_RESET = 0.1
SIGMA_DECAY_FACTOR = 0.88
SIGMA_RESET_VALUE = 4.0 # float

TEST_FUNCTION = "BEAM_HAUSDORFF"
NUMBER_OF_GENERATIONS = 15
ALPHA = 0.25 # survival rate
PROGRAMS_PER_GENERATION = 100
DATA_WRITER = None
SHOW_GRAPHS = True
RUN_ID = "0041"